# This is a basic workflow to help you get started with Actions

name: Continuous Integration (CI)

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest # macos windows

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3 # azure / GCP / AWS Dig

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo Starting Android GitHub ACtion

# 1. Java 17 / 18 
# 2. Android SDK 
# 3. ./gradlew assembleDebug -> build apk
   
      - name: Set Up JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu' # See 'Supported distributions' for available options
          java-version: '17'
          cache: 'gradle'

      - name: Setup Android SDK
        uses: android-actions/setup-android@v3

        # 3 gradle ccommands for ANdroid apk building
      - name: Build and Test with Gradle
        run: |
          ./gradlew assembleDebug


      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
